---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by spencerminer.
--- DateTime: 4/19/20 6:56 PM
---

--[[ Lua code. See documentation: http://berserk-games.com/knowledgebase/scripting/ --]]

--[[ The OnLoad function. This is called after everything in the game save finishes loading.
Most of your script code goes here. --]]
function onload()
    --[[ print('Onload!') --]]
end

--[[ The Update function. This is called once per frame. --]]
function update ()
    --[[ print('Update loop!') --]]
end